export const Errors = {
  HANDLER_NOT_FOUND: 'HANDLER_NOT_FOUND',
  FILE_CREATE_URL_FAILED: 'FILE_CREATE_URL_FAILED',
  APP_NOT_FOUND: 'APP_NOT_FOUND',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
} as const;
